export enum AuthRepositoryEnum {
    MENU_REPOSITORY = 'MENU_REPOSITORY',
    USER_REPOSITORY = 'USER_REPOSITORY',
    TRANSACTIONAL_CODE_REPOSITORY = 'TRANSACTIONAL_CODE_REPOSITORY'  
  }

  export enum CoreRepositoryEnum {
    CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',
    TIME_REPOSITORY = 'TIME_REPOSITORY',
    TIME_DETAIL_REPOSITORY = 'TIME_DETAIL_REPOSITORY',
    ALICUOTAS_REPOSITORY = 'ALICUOTAS_REPOSITORY',
    LOTE_REPOSITORY = 'LOTE_REPOSITORY' 
  }
